src/authe/urls.py
from django.urls import path
from .views import register, confirm_email, log_in, log_out


app_name = 'authe'

urlpatterns = [
    path('register/', register, name = 'register'),
    path('confirm/<str:code>', confirm_email, name = 'confirm'),
    path('log_in/', log_in, name='login'),
    path('log_out/', log_out, name = 'logout'),
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authe/', include('authe.urls')),
    path('', include('shop.urls')),
]

src/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path("", all_products, name = 'all_products'),
    path("product_info/<int:product_id>", product_info, name = 'product_info'),
    path("my_cart/", my_cart, name = 'my_cart'),
    path("add_to_cart", add_to_cart, name = 'add_to_cart')
]

src/shop/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from authe.models import Author

class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='категории', blank=False)

    class Meta:
        verbose_name = 'категоория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return f"{self.name}"



class Size(models.Model):
    name = models.CharField(max_length=10, verbose_name='размер', blank=False)

    class Meta:
        verbose_name = 'размер'
        verbose_name_plural = 'размеры'

    def __str__(self):
        return f"{self.name}"

class Color(models.Model):
    name = models.CharField(max_length=20, verbose_name='цвет', blank=False)

    class Meta:
        verbose_name = 'цвет'
        verbose_name_plural = 'цвета'

    def __str__(self):
        return f"{self.name}"



class Product(models.Model):
    name = models.CharField(max_length=30, verbose_name='одежда')
    description = models.TextField(max_length=1000, verbose_name='описание')
    category = models.ForeignKey(Category, on_delete=CASCADE, related_name='категории')
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='цена')
    color = models.ManyToManyField(Color, verbose_name='цвет')
    available = models.BooleanField(default=True)
    image = models.ImageField(upload_to='images', blank=True)
    size = models.ManyToManyField(Size, verbose_name='размеры')

    class Meta:
        verbose_name_plural = 'одежда'

    def __str__(self):
        return f"{self.name}"


class Cart(models.Model):
    STATUS_CHOICES = (
        ('created', 'Created'), 
        ('progress', 'Progress'),
        ('finished', 'Finished'),
        ('canceled', 'Canceled') 
    ) 
    owner = models.ForeignKey(Author, on_delete=CASCADE, related_name='владелец')
    email = models.EmailField(unique=True, verbose_name='Почта')
    created = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created')

    class Meta:
        verbose_name = 'корзина'
        verbose_name_plural = 'корзины'

    def __str__(self):
        return f"{self.owner}"

class CartProduct(models.Model):
    product = models.ForeignKey(Product, related_name='cart_product', on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, related_name='cart_product', on_delete=models.CASCADE)
    count = models.IntegerField()

    class Meta:
        verbose_name = 'одежда в корзине'
        verbose_name_plural = 'одежда в корзине'

    def __str__(self):
        return f"{self.product_name}"

src/shop/views.py
from django.forms.widgets import EmailInput
from django.shortcuts import render, redirect
from .models import Category, Size, Product, Cart, CartProduct, Color
from authe.views import *

def html_data():
    return {'category':Category.objects.all(), 'size':Size.objects.all(), 'color':Color.objects.all()}

def all_products(request):
    if request.user.is_authenticated:
        products = Product.objects.filter(available = True)
        return render(request, 'all_products.html', {'products':products, 'dropdown': html_data()})
    elif request.user.is_authenticated == False:
        return redirect('authe:register')

def product_info(request, product_id):
    product = Product.objects.get(id = product_id)
    return render(request, "product_info.html", {"product":product, 'dropdown':html_data()})

def products_filter(request, category_id):
    products = Product.objects.filter(category__id = category_id)
    return render(request, 'products_filter.html', {'products':products, 'dropdown':html_data()})

def cart_create(request):
    cart = Cart.objects.create(
        owner = request.user,
        email = request.user.email
    )
    if cart.is_valid():
        pass
    cart.save()
    return cart_create(request)

# def cart_delete(request):
#     if log_out(request):
#         cart = Cart.objects.filter(owner = request.user)
#         cart.delete()
#         return render(request, 'index.html')

def add_to_cart(request):
    if request.method == 'POST':
        product = Product.objects.get(id = request.POST['product'])
        cart_product = CartProduct.objects.create(
            cart = request.user.cart,
            product = product,
            count = 1
        )
        cart_product.save()

def my_cart(request):
    cart = Cart.objects.get(owner = request.user)
    products = CartProduct.objects.filter(cart = cart)
    return render(request, 'my_cart.html', {'cart':cart, 'products':products, 'dropdown':html_data()})

src/shop/templates/all_products.html
{% extends 'index.html' %}
{% block content %}
<h1>Clothes</h1>

{% for product in products %}
<a href="{% url 'shop:product_info' product_id=product.id %}">{{product.name}}</a>
<a href="{% url 'shop:add_to_cart' %}" >add to cart</a>
<p></p>
{% endfor %}

{% endblock %}

src/shop/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">{{user.username}}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'shop:all_products' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            {% if user.is_authenticated == True %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authe:logout' %}">logout</a>
            </li>
            {% endif %}
            {% if user.is_authenticated == False %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authe:register' %}">register</a>
            </li>
            {% endif %}
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

{% for category in dropdown.category %}
<a href='#'>{{category.name}}</a>
{% endfor %}

{% block content %}
{% endblock %}
</body>
</html>

src/shop/templates/my_cart.html
{% extends 'index.html' %}
{% block content %}

{{cart.owner}}

{% for product in products %}
{{product.name}}
{% endfor %}

{% endblock %}

src/shop/templates/product_info.html
{% extends 'index.html' %}
{% block content %}
<h3>Name - {{product.name}}</h3>
<h4>Description - {{product.description}}</h4>
<h4>Price - {{product.price}}</h4>
<h4>Category - {{product.category}}</h4>

Colors:
{% for color in product.color.all %}
<h5>{{color.name}}</h5>
{% endfor %}

Sizes:
{% for size in product.size.all %}
<h5>{{size.name}}</h5>
{% endfor %}


{% endblock %}